#!/bin/bash

BONSAI_NAME="bonsai"
BONSAI_VERSION="0.0.3"

source /usr/bonsai/_build.sh

opt_install ()
{
  info "Bonsai-$BONSAI_VERSION"

  params=${*//\'}
  params=${params/ -- / }
  info "Installing: $params"
  for elem in $params ;do
    PN=$elem
    export PN

    if [ "$PN" == "--" ]; then
      return
    fi
    
    PKG="$BONSAI_DIR/pkgtree/${PN}.pkg"
    if [ ! -f "$PKG" ]; then
      pwd
      msg "package \"$PN\" not found!"
      exit 1
    fi

    source $PKG

    setup
    if [ $pretend_flag == yes ];then
      fetch_pkg
      exit 0
    fi
    
    prepare
    
    info "configure phase"
    configure
    
    info "building phase"
    build
    
    if [ $check_flag == yes ];then
      info "checking phase"
      check
    fi
    
    info "merge phase"
    merge
    
    extra
    
    if [ $noclean_flag == no ];then
      info "cleaning..."
      clean
    else
      cd -
    fi
  done
  exit 0
}

opt_help()
{
  info "$BONSAI_NAME-$BONSAI_VERSION\n\
bonsai -I pkgname -> install          [DONE]
bonsai -R pkgname -> remove           [TODO]
bonsai -Q pattern -> search           [TODO]
bonsai -L         -> list installed.  [TODO]
bonsai -U         -> update system    [TODO]
bonsai -S         -> sync files.      [TODO]

--pretend / -p                        [DONE]
--quiet / -q no compiling output      [TODO]
--version / -v show version           [DONE]
--help / -h  show help                [DONE]
--noclean / -n do not run clean       [DONE]
--check / -c run checks after build.  [DONE]"
  exit 0
}

opt_version()
{
  info "Bonsai-$BONSAI_VERSION"
  exit 0
}

install_flag=no
remove_flag=no
query_flag=no
noclean_flag=no
check_flag=no
pretend_flag=no

if ! options=$(getopt -o I:R:Q:ncphv -l \
             install:,remove:,query:,noclean,check,pretend,help,version -- "$@")
then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -I|--install) shift; opt_install "$*" ;;
    -R|--remove) remove_flag=yes; info "not implemented" shift;;
    -Q|--query) query_flag=yes ; info "not implmented" shift;;
    -n|--noclean) noclean_flag=yes ;;
    -c|--check) check_flag=yes ;;
    -p|--pretend) pretend_flag=yes ;;
    -h|--help) opt_help ;;
    -v|--version) opt_version ;;
    (--) shift; break;;
    (-*) echo "$BONSAI_NAME: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done
