#!/bin/bash

BONSAI_NAME="Bonsai"
BONSAI_VERSION="0.0.8-2"

source /etc/bonsai/bonsai.conf
source /usr/bonsai/_functions.sh
source /usr/bonsai/_build.sh

info "Bonsai-$BONSAI_VERSION"
opt_install ()
{
  check_user

  params=${*//\'}
  params=${params/ -- / }
  info "* Installing: $params"
  for elem in $params ;do
    PN=$elem
    export PN

    if [ "$PN" == "--" ]; then
      return
    fi

    PKG=""
    if [[ "$PN" == *.pkg ]]; then
      PKG="./$PN"
      PN=${PN::-4}
    else
      PKG="$BONSAI_DIR/pkgtree/${PN}.pkg"
    fi

    if [ ! -f "$PKG" ]; then
      pwd
      msg "* This package: \"$PN\" was not found!"
      msg "* To check availible packages, use --packages option"
      exit 1
    fi

    QUIET=""
    if [ $quiet_flag == "yes" ];then
       QUIET=">> /dev/null 2>&1"
    fi

    eval "source $PKG $QUIET"

    eval "setup $QUIET"

    if [ $pretend_flag == yes ];then
      fetch_pkg && echo "" || opfault "fetch"
      exit 0
    fi

    eval "prepare $QUIET"
    if [ $confirm_flag == "yes" ];
    then
			 echo -ne "\033[33m* Would you like to install "
			 echo -ne "\033[0m\033[32m$PN\033[0m [Y/n]? "
       read INSTALL
       case $INSTALL in
							 "Y"|"y") echo "";;
							 "N"|"n") 
											 info "Aborting..."
											 exit 0;;
       esac
    else
       echo ""
    fi

    info "* Source configure phase..."
    eval "configure $QUIET && echo \"\" || opfault \"configure\""

    info "* Source build phase..."
    eval "build $QUIET && echo \"\" || opfault \"build\""

    if [ $check_flag == yes ];then
      info "* Checking phase..."
      eval "check $QUIET"
    fi
    
    info "* Install/Merge phase..."
    eval "merge $QUIET && echo \"\" || opfault \"mergepkg\""

    eval "extra $QUIET"

    if [ $noclean_flag == no ];then
      info "* Cleaning..."
      eval "clean $QUIET"
    else
      cd -
    fi
    mem_installed
  done
}

opt_help()
{
  info "\
$BONSAI_NAME package manager - Help page
+------------------------------------------+
     <opt> [arg]    [action]        {status}
bonsai -I pkgname -> install          [DONE]
bonsai -R pkgname -> remove           [TODO]
bonsai -Q pattern -> search           [DONE]
bonsai -D pattern -> search + desc    [DONE]
bonsai -L         -> list installed.  [DONE]
bonsai -U         -> update system    [DONE]
bonsai -S         -> sync files.      [DONE]

+------------------------------------------+

Other arguments
+-------------------------------------------------+
--pretend / -p                               [DONE]
--quiet / -q     -> no compiling output      [DONE]
--version / -v   -> show version             [DONE]
--help / -h      -> show help                [DONE]
--noclean / -n   -> do not run clean         [DONE]
--check / -c     -> run checks after build.  [DONE]
--packages       -> lists all avail. pkgs    [DONE]
--confirm /-a    -> asks for install         [DONE]
+-------------------------------------------------+

Bonsai directories
+----------------------------------------------------------------+
/etc/bonsai : directory that contains config files
|--> bonsai.conf : shellscript with config for bonsai

/usr/bonsai : directory that contains pkgtree and some code
|--> pkgtree/ : directory that contains *.pkg files(sh)
 |--> *.pkg : shellscripts that contains instructions for merging
|--> _*.sh : code used (such as headers in C) in Bonsai  

/var/bonsai : contains info about installed packages
|--> installed : each file mean installed package
+----------------------------------------------------------------+"
  exit 0
}

opt_version()
{
  info "Using bonsai version: $BONSAI_NAME-$BONSAI_VERSION"
  exit 0
}

opt_pkglist()
{
  LIST_PACKAGES=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g')
  info "\nAvailible packages\n**********"
  info "$LIST_PACKAGES"
  info "**********\nAvailible packages"
}

opt_query()
{
  param=${*//\'}
  param=${param/ -- /}
  SEARCH_PKG=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g' | grep $param)
  QUERY_RES=$SEARCH_PKG
  info "* You searched for: $param\n"
  for i in $QUERY_RES ;do
         echo -n "--> "; info $i
  done
}

opt_sync ()
{
  check_user
  info "* Syncing pkgtree: $BONSAI_TREE"

  if which git >/dev/null; then
     pushd . >/dev/null
     cd $BONSAI_TREE
     if [ -d .git ]; then
       git pull
     else
       msg "Cloning repo to $BONSAI_TREE"
       git clone $BONSAI_GIT_REPO ./
     fi
     popd >/dev/null
  else
     info "* Git is not available, please install!"
     exit 1
  fi
}

list_desc()
{
  [[ $DESCRIPTION == "" ]] && DESCRIPTION="N/A"
  [[ $HOMEPAGE == "" ]] && HOMEPAGE="N/A"
  [[ $VERSION == "" ]] && VERSION="N/A"
  [[ $LICENSE == "" ]] && LICENSE="N/A"

  echo -n "Name: " ;info "$param" | sed "s/.pkg//"
  echo -n "Description: ";info "$DESCRIPTION"
  echo -n "Homepage: " ;info "$HOMEPAGE"
  echo -n "Version: " ;info "$VERSION"
  echo -n "License: " ;info "$LICENSE"

  echo ""
}

opt_querydesc()
{
  param=${*//\'}
  param="${param/ -- /}.pkg"
  info "* You searched description for: $param\n" | sed "s/.pkg//"
  source $BONSAI_DIR/pkgtree/$param 2>/dev/null && list_desc || exit 3
}

opt_listinstalled()
{
  check_user
  LISTDIR=$(ls -l $INSTALLED_DIR | awk '{ print $9 }')
  info "* Installed packages by Bonsai\n"
  for i in $LISTDIR;
  do
          echo -n "--> "; info $i
  done
}

opt_upgrade()
{
	check_user
	info "* Syncing repositories before system upgrade... Wait..."
	opt_sync >>/dev/null
	info "* Done... Checking packages"
	sleep 1
	LIST_INSTALLED_PKGS=$(ls -l $INSTALLED_DIR | awk '{ print $9 }')
	for listpkg in $LIST_INSTALLED_PKGS; 
	do
					source $INSTALLED_DIR/$listpkg
					source /usr/bonsai/pkgtree/$listpkg\.pkg
					PKG_CURRENT_VERSION=$CURRENT_VERSION
					PKG_NEXT=$VERSION
					if [[ $PKG_CURRENT_VERSION != $PKG_NEXT ]];
					then
									info "* [UPGRADE] Update for $listpkg availible!"
									info "* Upgrading $listpkg from $PKG_CURRENT_VERSION to $PKG_NEXT ..."
									opt_install $listpkg
									sed -i "s/CURRENT_VERSION=\"$PKG_CURRENT_VERSION\"/CURRENT_VERSION=\"$PKG_NEXT\"/g" $INSTALLED_DIR/$listpkg
					elif [[ $PKG_CURRENT_VERSION == $PKG_NEXT ]];
					then
									info "* [OK] $listpkg is already updated :) no upgrade required"
					fi
	done
	info "* Done"
}

install_flag=no
remove_flag=no
query_flag=no
noclean_flag=no
check_flag=no
pretend_flag=no
searchdesc_flag=no
quiet_flag=no
confirm_flag=no

if ! options=$(getopt -o I:R:Q:D:SLUqncphva -l \
             install:,remove:,query:,desc:,sync,noclean,check,pretend,help,version,packages,installed,quiet,upgrade,confirm -- "$@")
then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -I|--install) shift; opt_install "$*" ;;
    -R|--remove) remove_flag=yes; info "* This operation is not implemented yet." shift;;
    -Q|--query) query_flag=yes ; opt_query "$2" ;;
    -D|--desc) searchdesc_flag=yes ; opt_querydesc "$2" ;;
    -S|--sync) opt_sync ;;
    -n|--noclean) noclean_flag=yes ;;
    -c|--check) check_flag=yes ;;
    -p|--pretend) pretend_flag=yes ;;
    -h|--help) opt_help ;;
    -v|--version) opt_version ;;
    --packages) opt_pkglist ;;
    -L|--installed) opt_listinstalled;;
    -q|--quiet) quiet_flag=yes;;
		-U|--upgrade) opt_upgrade;;
		-a|--confirm) confirm_flag=yes;;
    (--) shift; break;;
    (-*) echo "$BONSAI_NAME: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done
