#!/bin/bash

BONSAI_NAME="Bonsai"
BONSAI_VERSION="0.0.7"

source /etc/bonsai/bonsai.conf
source /usr/bonsai/_functions.sh
source /usr/bonsai/_build.sh

opt_install ()
{
  check_user
  info "Bonsai-$BONSAI_VERSION"

  params=${*//\'}
  params=${params/ -- / }
  info "* Installing: $params"
  for elem in $params ;do
    PN=$elem
    export PN

    if [ "$PN" == "--" ]; then
      return
    fi
    
    PKG="$BONSAI_DIR/pkgtree/${PN}.pkg"
    if [ ! -f "$PKG" ]; then
      pwd
      msg "* This package: \"$PN\" was not found!"
      msg "* To check availible packages, use --packages option"
      exit 1
    fi

    source $PKG

		if [[ $quiet_flag == "yes" ]];
		then
						setup>>/dev/null
		else
						setup
		fi

    if [ $pretend_flag == yes ];then
      fetch_pkg && echo "" || opfault "fetch"
      exit 0
    fi
		
		if [[ $quiet_flag == "yes" ]];
		then
						prepare >> /dev/null
		else
						prepare
		fi
    
    info "* Source configure phase..."
		if [[ $quiet_flag == "yes" ]];
		then
						configure >> /dev/null && echo "" || opfault "configure"
		else
						configure && echo "" || opfault "configure"
		fi

    info "* Source build phase..."
		if [[ $quiet_flag == "yes" ]];
		then
						build >> /dev/null && echo "" || opfault "build"
		else
						build && echo "" || opfault "build"
		fi

    if [ $check_flag == yes ];then
      info "* Checking phase..."
			if [[ $quiet_flag == "yes" ]];
			then
							check >> /dev/null
			else
							check
			fi
    fi
    
    info "* Install/Merge phase..."
		if [[ $quiet_flag == "yes" ]];
		then
						merge >>/dev/null && echo "" || opfault "mergepkg"
		else
						merge && echo "" || opfault "mergepkg"
		fi

		if [[ $quiet_flag == "yes" ]];
		then
						extra>>/dev/null
		else
						extra
		fi
    
    if [ $noclean_flag == no ];then
      info "* Cleaning..."
      if [[ $quiet_flag == "yes" ]];
			then
							clean >>/dev/null
			else
							clean
			fi
    else
      cd -
    fi
		mem_installed 
  done
  exit 0
}

opt_help()
{
  info "$BONSAI_NAME-$BONSAI_VERSION\n\
$BONSAI_NAME package manager - Help page
+------------------------------------------+
     <opt> [arg]    [action]        {status}
bonsai -I pkgname -> install          [DONE]
bonsai -R pkgname -> remove           [TODO]
bonsai -Q pattern -> search           [DONE]
bonsai -D pattern -> search + desc    [DONE]
bonsai -L         -> list installed.  [DONE]
bonsai -U         -> update system    [TODO]
bonsai -S         -> sync files.      [DONE]

+------------------------------------------+

Other arguments
+-------------------------------------------------+
--pretend / -p                               [DONE]
--quiet / -q     -> no compiling output      [DONE]
--version / -v   -> show version             [DONE]
--help / -h      -> show help                [DONE]
--noclean / -n   -> do not run clean         [DONE]
--check / -c     -> run checks after build.  [DONE]
--packages       -> lists all avail. pkgs    [DONE]
+-------------------------------------------------+

Bonsai directories
+----------------------------------------------------------------+
/etc/bonsai : directory that contains config files
|--> bonsai.conf : shellscript with config for bonsai

/usr/bonsai : directory that contains pkgtree and some code
|--> pkgtree/ : directory that contains *.pkg files(sh)
 |--> *.pkg : shellscripts that contains instructions for merging
|--> _*.sh : code used (such as headers in C) in Bonsai  

/var/bonsai : contains info about installed packages
|--> installed : each file mean installed package
+----------------------------------------------------------------+"
  exit 0
}

opt_version()
{
  info "Using bonsai version: $BONSAI_NAME-$BONSAI_VERSION"
  exit 0
}

opt_pkglist()
{
  LIST_PACKAGES=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g')
  info "$BONSAI_NAME-$BONSAI_VERSION"
  info "\nAvailible packages\n**********"
  info "$LIST_PACKAGES"
  info "**********\nAvailible packages"
}

opt_query()
{
  param=${*//\'}
  param=${param/ -- /}
  SEARCH_PKG=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g' | grep $param)
  QUERY_RES=$SEARCH_PKG
  info "$BONSAI_NAME-$BONSAI_VERSION"
  info "* You searched for: $param\n"
  for i in $QUERY_RES ;do
         echo -n "--> "; info $i
  done
}

opt_sync ()
{
	check_user
  info "$BONSAI_NAME-$BONSAI_VERSION"
  info "* Syncing pkgtree: $BONSAI_TREE"

  if which git >/dev/null; then
     pushd . >/dev/null
     cd $BONSAI_TREE
     if [ -d .git ]; then
       git pull
     else
       msg "Cloning repo to $BONSAI_TREE"
       git clone $BONSAI_GIT_REPO ./
     fi
     popd >/dev/null
  else
     info "* Git is not available, please install!"
     exit 1
  fi
}

list_desc()
{
  [[ $DESCRIPTION == "" ]] && DESCRIPTION="N/A"
  [[ $HOMEPAGE == "" ]] && HOMEPAGE="N/A"
  [[ $VERSION == "" ]] && VERSION="N/A"
  [[ $LICENSE == "" ]] && LICENSE="N/A"

  echo -n "Name: " ;info "$param" | sed "s/.pkg//"
  echo -n "Description: ";info "$DESCRIPTION"
  echo -n "Homepage: " ;info "$HOMEPAGE"
  echo -n "Version: " ;info "$VERSION"
  echo -n "License: " ;info "$LICENSE"

  echo ""
}

opt_querydesc()
{
  param=${*//\'}
  param="${param/ -- /}.pkg"
  info "$BONSAI_NAME-$BONSAI_VERSION"
  info "* You searched description for: $param\n" | sed "s/.pkg//"
  source $BONSAI_DIR/pkgtree/$param 2>/dev/null && list_desc || exit 3
}

opt_listinstalled()
{
	check_user
	LISTDIR=$(ls -l $INSTALLED_DIR | awk '{ print $9 }')
	info "Bonsai-$BONSAI_VERSION"
	info "* Installed packages by Bonsai\n"
	for i in $LISTDIR;
	do
					echo -n "--> "; info $i
	done
}
install_flag=no
remove_flag=no
query_flag=no
noclean_flag=no
check_flag=no
pretend_flag=no
searchdesc_flag=no
quiet_flag=no

if ! options=$(getopt -o I:R:Q:D:SLqncphv -l \
             install:,remove:,query:,desc:,sync,noclean,check,pretend,help,version,packages,installed,quiet -- "$@")
then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -I|--install) shift; opt_install "$*" ;;
    -R|--remove) remove_flag=yes; info "* This operation is not implemented yet." shift;;
    -Q|--query) query_flag=yes ; opt_query "$2" ;;
    -D|--desc) searchdesc_flag=yes ; opt_querydesc "$2" ;;
    -S|--sync) opt_sync ;;
    -n|--noclean) noclean_flag=yes ;;
    -c|--check) check_flag=yes ;;
    -p|--pretend) pretend_flag=yes ;;
    -h|--help) opt_help ;;
    -v|--version) opt_version ;;
    --packages) opt_pkglist ;;
    -L|--installed) opt_listinstalled;;
		-q|--quiet) quiet_flag=yes;;
    (--) shift; break;;
    (-*) echo "$BONSAI_NAME: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done
