#!/bin/bash

BONSAI_NAME="Bonsai"
BONSAI_VERSION="0.0.8-5"
BONSAI_CONF="/etc/bonsai/bonsai.conf"

source $BONSAI_CONF
source /usr/bonsai/_functions.sh
source /usr/bonsai/_build.sh

#banner

opt_install ()
{
  check_user

  params=${*//\'}
  params=${params/ -- / }
  info "* Installing: $params"
  for elem in $params ;do
    PN=$elem
    export PN

    if [ "$PN" == "--" ]; then
      return
    fi

    PKG=""
    if [[ "$PN" == *.pkg ]]; then
      PKG="./$PN"
      PN=${PN::-4}
    else
      PKG="$BONSAI_DIR/pkgtree/${PN}.pkg"
    fi

    if [ ! -f "$PKG" ]; then
      pwd
      msg "* This package: \"$PN\" was not found!"
      msg "* To check availible packages, use --packages option"
      exit 1
    fi

    QUIET=""
    if [ $quiet_flag == "yes" ];then
       QUIET=">> /dev/null 2>&1"
    fi

    eval "source $PKG $QUIET"

	for index in $DEPS;
	do
		msg "* Installing dependencies *"
		if [ $quiet_flag == "yes" ];
		then
				bonsai -qI $index || exit 3
		else
				bonsai -I $index || exit 3
		fi

	done

    eval "setup $QUIET"

    if [ $pretend_flag == yes ];then
      fetch_pkg && echo "" || opfault "fetch"
      exit 0
    fi

    eval "prepare $QUIET"
    if [ $confirm_flag == "yes" ];then
    echo -ne "\033[33m* Would you like to install "
    echo -ne "\033[0m\033[32m$PN\033[0m [Y/n]? "
       read INSTALL
       case $INSTALL in
       # "Y"|"y") echo "";;
       "N"|"n")
         info "Aborting..."
         exit 0;;
       esac
    fi

		#This function MUST Not be evaluated for $QUIET!
		if_editor

    info "* Source configure phase..."
    eval "configure $QUIET && echo \"\" || opfault \"configure\""

		info "* Source build phase..."
		info "* Using make flags : $MAKE_FLAGS"
    eval "build  $QUIET && echo \"\" || opfault \"build\""

    if [ $check_flag == yes ];then
      info "* Checking phase..."
      eval "check $QUIET"
    fi

    info "* Install/Merge phase..."
    eval "merge $QUIET && echo \"\" || opfault \"mergepkg\""

    eval "extra $QUIET"

    if [ $noclean_flag == no ];then
      info "* Cleaning..."
      eval "clean $QUIET"
    else
      cd -
    fi
    mem_installed
  done
}

opt_help()
{
  info "\
$BONSAI_NAME package manager - Help page
+------------------------------------------+
     <opt> [arg]    [action]        {status}
bonsai -I pkgname -> install          [DONE]
bonsai -R pkgname -> remove           [TODO]
bonsai -Q pattern -> search           [DONE]
bonsai -D pattern -> search + desc    [DONE]
bonsai -L         -> list installed.  [DONE]
bonsai -U         -> update system    [DONE]
bonsai -S         -> sync files.      [DONE]

+------------------------------------------+

Other arguments
+-------------------------------------------------+
--pretend / -p                               [DONE]
--quiet / -q     -> no compiling output      [DONE]
--version / -v   -> show version             [DONE]
--help / -h      -> show help                [DONE]
--noclean / -n   -> do not run clean         [DONE]
--check / -c     -> run checks after build.  [DONE]
--packages       -> lists all avail. pkgs    [DONE]
--confirm /-a    -> asks for install         [DONE]
--conf/-e        -> shows env. settings      [DONE]
+-------------------------------------------------+

Bonsai directories
+----------------------------------------------------------------+
/etc/bonsai : directory that contains config files
|--> bonsai.conf : shellscript with config for bonsai

/usr/bonsai : directory that contains pkgtree and some code
|--> pkgtree/ : directory that contains *.pkg files(sh)
 |--> *.pkg : shellscripts that contains instructions for merging
|--> _*.sh : functions used by bonsai

/var/bonsai : contains info about installed packages
|--> installed : each file mean installed package
+----------------------------------------------------------------+"
  exit 0
}

opt_version()
{
  info "Using bonsai version: $BONSAI_NAME-$BONSAI_VERSION"
  exit 0
}

opt_pkglist()
{
  LIST_PACKAGES=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g')
  info "\nAvailible packages\n**********"
  info "$LIST_PACKAGES"
  info "**********\nAvailible packages"
}

opt_query()
{
  param=${*//\'}
  param=${param/ -- /}
  SEARCH_PKG=$(ls $BONSAI_DIR/pkgtree -l 2>/dev/null | awk '{ print $9 }' | sed 's/.pkg//g' | grep $param)
  QUERY_RES=$SEARCH_PKG
  info "* You searched for: $param\n"
  for i in $QUERY_RES ;do
         echo -n "--> "; info $i
  done
}

opt_sync ()
{
  check_user
  info "* Syncing pkgtree: $BONSAI_TREE"

  if which git >/dev/null; then
     pushd . >/dev/null
     cd $BONSAI_TREE
     if [ -d .git ]; then
       git pull >/dev/null && info "* Repository syncing done :) " || exit 2
     else
       msg "Cloning repo to $BONSAI_TREE"
       git clone $BONSAI_GIT_REPO ./ >/dev/null && info "* Repository cloning done :) " || exit 2
     fi
     popd >/dev/null
  else
     info "* Git is not available, please install!"
     exit 1
  fi
}

list_desc()
{
  LOCATION=$BONSAI_DIR/pkgtree/$param

  [[ $DESCRIPTION == "" ]] && DESCRIPTION="N/A"
  [[ $HOMEPAGE == "" ]] && HOMEPAGE="N/A"
  [[ $VERSION == "" ]] && VERSION="N/A"
  [[ $LICENSE == "" ]] && LICENSE="N/A"

  echo -n "Name: " ;info "$param" | sed "s/.pkg//"
  echo -n "Description: ";info "$DESCRIPTION"
  echo -n "Homepage: " ;info "$HOMEPAGE"
  echo -n "Version: " ;info "$VERSION"
  echo -n "License: " ;info "$LICENSE"
  echo -n "Pkgfile located at: $LOCATION"

  echo ""
}

opt_querydesc()
{
  param=${*//\'}
  param="${param/ -- /}.pkg"
  info "* You searched description for: $param\n" | sed "s/.pkg//"
  source $BONSAI_DIR/pkgtree/$param 2>/dev/null && list_desc || exit 3
}

opt_listinstalled()
{
  check_user
  LISTDIR=$(ls -l $INSTALLED_DIR | awk '{ print $9 }')
  info "* Installed packages by Bonsai\n"
  for i in $LISTDIR;
  do
          echo -n "--> "; info $i
  done
}

opt_upgrade()
{
 check_user
 info "* Syncing repositories before system upgrade... Wait..."
 opt_sync >>/dev/null
 info "* Done... Checking packages"
 sleep 1
 LIST_INSTALLED_PKGS=$(ls -l $INSTALLED_DIR | awk '{ print $9 }')
 for elem in $LIST_INSTALLED_PKGS;
 do
     source $INSTALLED_DIR/$elem
     CURRENT_VERSION=$VERSION
     source /usr/bonsai/pkgtree/$elem\.pkg
     if [[ $CURRENT_VERSION != $VERSION ]];
     then
         info "* [UPGRADE] Update for $elem availible!"
         info "* Upgrading $elem from $CURRENT_VERSION to $VERSION ..."
         opt_install $elem
         #TODO overwrite...
         sed -i "s/VERSION=\"$CURRENT_VERSION\"/VERSION=\"$VERSION\"/g" $INSTALLED_DIR/$elem
     elif [[ $PKG_CURRENT_VERSION == $PKG_NEXT ]];
     then
         info "* [OK] $elem is already updated :) no upgrade required"
     fi
 done
 info "* Done"
}

opt_show_conf()
{
 check_user

 info "* From $BONSAI_CONF"
 info "* $BONSAI_NAME Settings... "
 echo "===DIRECTORIES==="
 info "--> Main Directory : $BONSAI_DIR"
 info "--> Var Directory  : $VAR_DIR"
 info "--> Installed pkgs : $INSTALLED_DIR"
 info "--> Sources dir    : $SRC_DIR"
 echo "===PACKAGES==="
 info "--> Package tree   : $BONSAI_TREE"
 info "--> Package tree repo : $BONSAI_GIT_REPO"
 echo "===SOURCES==="
 info "--> Build temp. dir : $BUILD_DIR"
 echo "===OTHER==="
 info "--> Using editor    : $CONFIG_EDITOR"
 info "--> Make flags      : $MAKE_FLAGS"
}

install_flag=no
remove_flag=no
query_flag=no
noclean_flag=no
check_flag=no
pretend_flag=no
searchdesc_flag=no
quiet_flag=no
confirm_flag=no

if ! options=$(getopt -o I:R:Q:D:SLUqncphvae -l \
             install:,remove:,query:,desc:,sync,noclean,check,pretend,help,version,packages,installed,quiet,upgrade,ask,conf -- "$@")
then
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -I|--install) shift; opt_install "$*" ;;
    -U|--upgrade) opt_upgrade;;
    -R|--remove) remove_flag=yes; info "* This operation is not implemented yet." shift;;
    -Q|--query) query_flag=yes ; opt_query "$2" ;;
    -L|--installed) opt_listinstalled;;
    -D|--desc) searchdesc_flag=yes ; opt_querydesc "$2" ;;
    -S|--sync) opt_sync ;;
    --packages) opt_pkglist ;;
    -n|--noclean) noclean_flag=yes ;;
    -c|--check) check_flag=yes ;;
    -p|--pretend) pretend_flag=yes ;;
    -h|--help) opt_help ;;
    -v|--version) opt_version ;;
    -q|--quiet) quiet_flag=yes;;
    -a|--ask) confirm_flag=yes;;
		-e|--conf) opt_show_conf ;;
    (--) shift; break;;
    (-*) echo "$BONSAI_NAME: error - unrecognized option $1" 1>&2; exit 1;;
    (*) break;;
    esac
    shift
done
